services:
  dashboard:
    build:
      context: .
      dockerfile: 3_data_consumption/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./3_data_consumption:/app
    working_dir: /app

  sentiment_api:
    build:
      context: .
      dockerfile: 4_deployment/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./4_deployment:/app
    working_dir: /app
